#!/usr/bin/env python3
"""
Automated File Organizer
------------------------
Recursively organizes files in a directory into category folders.

Features:
- Recursive traversal with pathlib
- Skips directories and symbolic links
- Extension-based categorization
- "Other" for unknown extensions
- Conflict-safe filename generation
- Permission/OS error handling
- Timestamped logging
- Summary report
- Command-line interface
- Dry-run mode
"""

from __future__ import annotations

import argparse
import logging
import os
import shutil
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Iterable

CATEGORIES = {
    ".py": "Python_Code",
    ".pyw": "Python_Code",
    ".js": "JavaScript",
    ".ts": "TypeScript",
    ".java": "Java_Code",
    ".c": "C_Code",
    ".h": "C_Code",
    ".cpp": "Cpp_Code",
    ".cc": "Cpp_Code",
    ".cxx": "Cpp_Code",
    ".html": "Web",
    ".htm": "Web",
    ".css": "Web",
    ".json": "Data",
    ".csv": "Data",
    ".xml": "Data",
    ".txt": "Documents",
    ".pdf": "Documents",
    ".doc": "Documents",
    ".docx": "Documents",
    ".xls": "Documents",
    ".xlsx": "Documents",
    ".ppt": "Documents",
    ".pptx": "Documents",
    ".jpg": "Images",
    ".jpeg": "Images",
    ".png": "Images",
    ".gif": "Images",
    ".bmp": "Images",
    ".webp": "Images",
    ".svg": "Images",
    ".mp3": "Audio",
    ".wav": "Audio",
    ".flac": "Audio",
    ".mp4": "Videos",
    ".mkv": "Videos",
    ".avi": "Videos",
    ".mov": "Videos",
    ".zip": "Archives",
    ".rar": "Archives",
    ".7z": "Archives",
    ".tar": "Archives",
    ".gz": "Archives",
}

@dataclass
class Summary:
    scanned: int = 0
    moved: int = 0
    planned: int = 0
    skipped: int = 0
    errors: int = 0
    by_category: dict[str, int] = field(default_factory=dict)

    def add_moved(self, category: str) -> None:
        self.moved += 1
        self.by_category[category] = self.by_category.get(category, 0) + 1

def configure_logging(log_file: Path) -> logging.Logger:
    logger = logging.getLogger("file_organizer")
    logger.setLevel(logging.INFO)
    for handler in logger.handlers[:]:
        handler.close()
        logger.removeHandler(handler)

    formatter = logging.Formatter(
        "%(asctime)s | %(levelname)s | %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
    )

    file_handler = logging.FileHandler(log_file, encoding="utf-8")
    file_handler.setFormatter(formatter)
    logger.addHandler(file_handler)

    console_handler = logging.StreamHandler()
    console_handler.setFormatter(formatter)
    logger.addHandler(console_handler)
    return logger

def is_safe_regular_file(path: Path) -> bool:
    """Return True only for real files, never symlinks."""
    try:
        return path.is_file() and not path.is_symlink()
    except OSError:
        return False

def iter_files(
    source: Path,
    logger: logging.Logger,
    excluded_paths: set[Path] | None = None,
) -> Iterable[Path]:
    """
    Recursively yield regular files while skipping symlinked files/directories.

    excluded_paths contains files generated by this program (for example the
    log/report) so they are never accidentally organized when they live inside
    the source directory.
    """
    excluded_paths = excluded_paths or set()

    for root, dirs, files in os.walk(source, topdown=True, followlinks=False):
        root_path = Path(root)

        # Never scan directories created/used by this organizer.
        dirs[:] = [
            d for d in dirs
            if d not in CATEGORIES.values() and d != "Other"
        ]

        for filename in files:
            path = root_path / filename
            try:
                try:
                    if path.resolve() in excluded_paths:
                        logger.info("Skipping organizer output file: %s", path)
                        continue
                except OSError:
                    pass

                if path.is_symlink():
                    logger.info("Skipping symbolic link: %s", path)
                    continue
                if path.is_file():
                    yield path
                else:
                    logger.info("Skipping non-regular file: %s", path)
            except OSError as exc:
                logger.error("Cannot inspect %s: %s", path, exc)

def category_for(path: Path) -> str:
    return CATEGORIES.get(path.suffix.lower(), "Other")

def unique_target(target_dir: Path, filename: str) -> Path:
    """
    Return a non-existing target path.

    Example:
        report.txt
        report_copy.txt
        report_copy_2.txt
        report_copy_3.txt
    """
    candidate = target_dir / filename
    if not candidate.exists():
        return candidate

    stem = Path(filename).stem
    suffix = Path(filename).suffix
    candidate = target_dir / f"{stem}_copy{suffix}"
    counter = 2

    while candidate.exists():
        candidate = target_dir / f"{stem}_copy_{counter}{suffix}"
        counter += 1

    return candidate

def organize_directory(
    source: Path,
    dry_run: bool,
    logger: logging.Logger,
    excluded_paths: set[Path] | None = None,
) -> Summary:
    summary = Summary()

    if not source.exists():
        raise FileNotFoundError(f"Source directory does not exist: {source}")
    if not source.is_dir():
        raise NotADirectoryError(f"Source path is not a directory: {source}")
    if source.is_symlink():
        raise ValueError("The source directory itself must not be a symbolic link.")

    # Take a snapshot before creating category directories. This prevents
    # newly-created folders/files from being reprocessed during the same run.
    try:
        files = list(iter_files(source, logger, excluded_paths))
    except OSError as exc:
        logger.exception("Unable to traverse source directory: %s", exc)
        summary.errors += 1
        return summary

    for item in files:
        summary.scanned += 1
        category = category_for(item)
        target_dir = source / category

        try:
            if not target_dir.exists():
                logger.info("Creating directory: %s", target_dir)
                if not dry_run:
                    target_dir.mkdir(parents=True, exist_ok=True)

            target_path = unique_target(target_dir, item.name)

            if dry_run:
                summary.planned += 1
                logger.info("[DRY-RUN] Would move %s -> %s", item, target_path)
                continue

            # Re-check the source immediately before moving, because a file
            # could have disappeared/changed since traversal.
            if not item.exists() or item.is_symlink():
                summary.skipped += 1
                logger.warning("Skipping unavailable/symlinked file: %s", item)
                continue

            # If a race created the target after unique_target(), calculate a
            # fresh safe name instead of overwriting it.
            target_path = unique_target(target_dir, item.name)
            shutil.move(str(item), str(target_path))

            summary.add_moved(category)
            logger.info("Moved %s -> %s", item, target_path)

        except (PermissionError, FileNotFoundError, OSError) as exc:
            summary.errors += 1
            logger.error("Failed to process %s: %s", item, exc)
        except Exception as exc:
            summary.errors += 1
            logger.exception("Unexpected error while processing %s: %s", item, exc)

    return summary

def write_summary(report_path: Path, summary: Summary, dry_run: bool) -> None:
    lines = [
        "AUTOMATED FILE ORGANIZER - SUMMARY REPORT",
        "=" * 48,
        f"Mode: {'DRY-RUN (no files moved)' if dry_run else 'LIVE'}",
        f"Files scanned: {summary.scanned}",
        f"Files moved: {summary.moved}",
        f"Files planned: {summary.planned}",
        f"Files skipped: {summary.skipped}",
        f"Errors: {summary.errors}",
        "",
        "Files by category:",
    ]

    if summary.by_category:
        for category, count in sorted(summary.by_category.items()):
            lines.append(f"  {category}: {count}")
    else:
        lines.append("  None")

    report_path.write_text("\n".join(lines) + "\n", encoding="utf-8")

def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Recursively organize files by extension."
    )
    parser.add_argument(
        "source",
        help="Path of the directory to organize",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Preview operations without moving files",
    )
    parser.add_argument(
        "--log-file",
        default="organizer.log",
        help="Log file path (default: organizer.log)",
    )
    parser.add_argument(
        "--report",
        default="organizer_report.txt",
        help="Summary report path (default: organizer_report.txt)",
    )
    return parser

def main() -> int:
    parser = build_parser()
    args = parser.parse_args()

    source = Path(args.source).expanduser()

    try:
        log_file = Path(args.log_file).expanduser()
        report_file = Path(args.report).expanduser()
        logger = configure_logging(log_file)

        excluded_paths: set[Path] = set()
        try:
            excluded_paths.add(log_file.resolve())
            excluded_paths.add(report_file.resolve())
        except OSError:
            pass

        logger.info("Starting organizer for: %s", source.resolve())
        logger.info("Dry-run: %s", args.dry_run)

        summary = organize_directory(
            source,
            args.dry_run,
            logger,
            excluded_paths=excluded_paths,
        )
        write_summary(report_file, summary, args.dry_run)

        print("\n--- ORGANIZATION SUMMARY ---")
        print(f"Files scanned : {summary.scanned}")
        print(f"Files moved   : {summary.moved}")
        print(f"Files planned : {summary.planned}")
        print(f"Files skipped : {summary.skipped}")
        print(f"Errors        : {summary.errors}")
        print(f"Log file      : {log_file.resolve()}")
        print(f"Report file   : {report_file.resolve()}")

        logger.info(
            "Finished | scanned=%d moved=%d planned=%d skipped=%d errors=%d",
            summary.scanned,
            summary.moved,
            summary.planned,
            summary.skipped,
            summary.errors,
        )

        # A non-zero status signals that some files failed, while successful
        # runs (including dry-runs) return zero.
        return 1 if summary.errors else 0

    except (FileNotFoundError, NotADirectoryError, PermissionError, ValueError) as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 2
    except OSError as exc:
        print(f"Operating-system error: {exc}", file=sys.stderr)
        return 2

if __name__ == "__main__":
    raise SystemExit(main())
